import Blog from "@/components/pages/blog";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Zagoo English - Blog",
  description: "Generated by create next app",
};
export default function Page() {
  return <Blog />;
}
