import Learning from "@/components/pages/learning-and-playing";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: `Zagoo English - Học cùng Zagoo`,
  description: "Generated by create next app",
};
export default function Page() {
  return <Learning />;
}
