import LoginForm from "@/components/ui/login-form";
import { Metadata } from "next";
import React from "react";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Zagoo English - Đăng nhập",
  description: "Generated by create next app",
};

export default async function Page() {
  const cookieUser = cookies().get("user");
  if (!cookieUser) {
    return <LoginForm />;
  }
  redirect(`/`);
}
