import Translate from "@/components/pages/translate";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Zagoo English - Dịch từ",
  description: "Generated by create next app",
};
export default function Page() {
  return <Translate />;
}
