import BlogDetail from "@/components/pages/blog/detail";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Zagoo English - Blog",
  description: "Generated by create next app",
};

export default function Page({ params }: { params: { id: number } }) {
  const { id } = params;
  return <BlogDetail id={id} />;
}
