import RegisterForm from "@/components/ui/register-form";
import { Metadata } from "next";
import React from "react";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Zagoo English - Đăng ký",
  description: "Generated by create next app",
};
export default function Page() {
  const cookieUser = cookies().get("user");
  if (!cookieUser) {
    return <RegisterForm />;
  }
  redirect(`/`);
}
