import UserProfile from "@/components/pages/profile";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import React from "react";
export const metadata: Metadata = {
  title: "Zagoo English - Trang cá nhân",
  description: "Generated by create next app",
};
export default function Page() {
  const cookieUser = cookies().get("user");
  if (cookieUser) {
    return <UserProfile />;
  }
  redirect(`/`);
}
